### ISSUE TITLE
Field type handler fallbacks

### ISSUE THREAD

**Issue by iherak** [netgen/NetgenOpenGraphBundle#1]
When defining field type handlers for a tag, it should be possible to define falback field identifier through parameters.

Something along the lines of:
- { handler: field_type/ezstring, tag: 'og:desription', params: [['line_intro', 'full_intro'], 'My fallback description'] }

Desired behaviour:
- handler checks whether line_intro is empty, if not, use it. If empty, check full_intro. If full_intro is empty, use fallback value defined as second parameter.

**Comment by emodric** [comment]
Fixed in #2
