### ISSUE TITLE
Unable to use RichText on description field

### ISSUE THREAD

**Issue by jbcr** [netgen/NetgenOpenGraphBundle#10]
In my content type, the description is stored in `RichText`. Howto use it for `og:descripton` balise ?

I have an error if I attempt to use `XmlText` or `TextBlock`.

**Comment by emodric** [comment]
Hi!

There is no built in handler to extract data from `ezrichtext` field type. It would need to be implemented.

What error are you getting with `ezxmltext` and text block?

**Comment by emodric** [comment]
Fixed in https://github.com/netgen/NetgenOpenGraphBundle/commit/2df6a27ac5cb2347fdfa98929c1d63eef9eb1d09
